sudo: required
dist: trusty
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=tiepie/debian-debootstrap
    matrix:
        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=stretch UNAME_ARCH=x86_64 VERSION=stretch
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=stretch UNAME_ARCH=arm64 VERSION=stretch
        - ARCH=armel INCLUDE=wget QEMU_ARCH=armeb SUITE=stretch UNAME_ARCH=armel VERSION=stretch
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=stretch UNAME_ARCH=armv7l VERSION=stretch
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=stretch UNAME_ARCH=i386 VERSION=stretch
        - ARCH=mipsel INCLUDE=wget QEMU_ARCH=mipsel SUITE=stretch UNAME_ARCH=mipsel VERSION=stretch
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=stretch UNAME_ARCH=mips64el VERSION=stretch

        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=buster UNAME_ARCH=x86_64 VERSION=buster
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=buster UNAME_ARCH=arm64 VERSION=buster
        - ARCH=armel INCLUDE=wget QEMU_ARCH=armeb SUITE=buster UNAME_ARCH=armel VERSION=buster
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=buster UNAME_ARCH=armv7l VERSION=buster
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=buster UNAME_ARCH=i386 VERSION=buster
        - ARCH=mipsel INCLUDE=wget QEMU_ARCH=mipsel SUITE=buster UNAME_ARCH=mipsel VERSION=buster
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=buster UNAME_ARCH=mips64el VERSION=buster

before_script:
    - sudo apt-get clean -y -qq
    - sudo apt-get update -qq
    - sudo apt-get dist-upgrade -y
    - echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get -yt bionic install qemu-user-static debootstrap
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -o "$UNAME_ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO:$ARCH-$SUITE; fi
