sudo: required
dist: trusty
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=tiepie/debian-debootstrap
        - DATE=$(date +'%Y%m%d')
    matrix:
        - ARCH=amd64    INCLUDE=wget QEMU_ARCH=x86_64   SUITE=stretch TIEPIE_ARCH=x86_64
        - ARCH=arm64    INCLUDE=wget QEMU_ARCH=aarch64  SUITE=stretch TIEPIE_ARCH=arm64
        - ARCH=armel    INCLUDE=wget QEMU_ARCH=armeb    SUITE=stretch TIEPIE_ARCH=armel
        - ARCH=armhf    INCLUDE=wget QEMU_ARCH=arm      SUITE=stretch TIEPIE_ARCH=armhf
        - ARCH=i386     INCLUDE=wget QEMU_ARCH=i386     SUITE=stretch TIEPIE_ARCH=x86
        - ARCH=mipsel   INCLUDE=wget QEMU_ARCH=mipsel   SUITE=stretch TIEPIE_ARCH=mipsel
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=stretch TIEPIE_ARCH=mips64el

        - ARCH=amd64    INCLUDE=wget QEMU_ARCH=x86_64   SUITE=buster  TIEPIE_ARCH=x86_64
        - ARCH=arm64    INCLUDE=wget QEMU_ARCH=aarch64  SUITE=buster  TIEPIE_ARCH=arm64
        - ARCH=armel    INCLUDE=wget QEMU_ARCH=armeb    SUITE=buster  TIEPIE_ARCH=armel
        - ARCH=armhf    INCLUDE=wget QEMU_ARCH=arm      SUITE=buster  TIEPIE_ARCH=armhf
        - ARCH=i386     INCLUDE=wget QEMU_ARCH=i386     SUITE=buster  TIEPIE_ARCH=x86
        - ARCH=mipsel   INCLUDE=wget QEMU_ARCH=mipsel   SUITE=buster  TIEPIE_ARCH=mipsel
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=buster  TIEPIE_ARCH=mips64el

before_script:
    - sudo apt-get clean -y -qq
    - sudo apt-get update -qq
    - sudo apt-get dist-upgrade -y
    - echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get -yt bionic install qemu-user-static debootstrap
script:
    - sudo ./update.sh -d "$DATE" -a "$ARCH" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -v "$TIEPIE_ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO:$ARCH-$SUITE && docker push $DOCKER_REPO:$ARCH-$SUITE-$DATE; fi
