sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.8.4
        - DOCKER_REPO=tiepie/debian-debootstrap
    matrix:
        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=jessie UNAME_ARCH=x86_64 VERSION=jessie
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=jessie UNAME_ARCH=arm64 VERSION=jessie
        - ARCH=armel INCLUDE=wget QEMU_ARCH=armeb SUITE=jessie UNAME_ARCH=armel VERSION=jessie
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=jessie UNAME_ARCH=armv7l VERSION=jessie
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=jessie UNAME_ARCH=i386 VERSION=jessie
        - ARCH=mipsel INCLUDE=wget QEMU_ARCH=mipsel SUITE=jessie UNAME_ARCH=mipsel VERSION=jessie

        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=sid UNAME_ARCH=x86_64 VERSION=sid
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=sid UNAME_ARCH=arm64 VERSION=sid
        - ARCH=armel INCLUDE=wget QEMU_ARCH=armeb SUITE=sid UNAME_ARCH=armel VERSION=sid
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=sid UNAME_ARCH=armv7l VERSION=sid
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=sid UNAME_ARCH=i386 VERSION=sid
        - ARCH=mipsel INCLUDE=wget QEMU_ARCH=mipsel SUITE=sid UNAME_ARCH=mipsel VERSION=sid
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=sid UNAME_ARCH=mips64el VERSION=sid

        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=stretch UNAME_ARCH=x86_64 VERSION=stretch
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=stretch UNAME_ARCH=arm64 VERSION=stretch
        - ARCH=armel INCLUDE=wget QEMU_ARCH=armeb SUITE=stretch UNAME_ARCH=armel VERSION=stretch
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=stretch UNAME_ARCH=armv7l VERSION=stretch
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=stretch UNAME_ARCH=i386 VERSION=stretch
        - ARCH=mipsel INCLUDE=wget QEMU_ARCH=mipsel SUITE=stretch UNAME_ARCH=mipsel VERSION=stretch
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=stretch UNAME_ARCH=mips64el VERSION=stretch

before_script:
    - echo "deb http://ftp.de.debian.org/debian sid main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 7638D0442B90D010
    - sudo apt-get update -qq
    - sudo apt-get -y install debootstrap qemu-user-static
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -o "$UNAME_ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO; fi
